### ISSUE TITLE
In spite of alerting `エラーしたよ`, actually it is saved

### ISSUE THREAD

**Issue by amutake** [rutan/potmum#3]
Hi, I found a bug when I tried to save an article like below.

```md
- foo
- 

bar
```

(NOTE: the second list-item has some spaces)

#### Reproduction

1. go to `新規作成` page and write above markdown to body.
2. click `下書き保存` then potmum alerts `エラーしたよ` (500).
3. go to `マイページ -> 未公開の記事` page then you will see the article.

#### Environment

- branch: replace_to_potmarkdown
- browser: Chrome v50 (OS X)

**Comment by rutan** [comment]
Thanks for the report 😃 

This is bug of `pot_markdown` gem 😭  ( markdown processor for Potmum. )
I fixed this in `pot_markdown v.0.1.5`  https://github.com/rutan/pot_markdown/commit/083dcb319ddbd8dcf1904db0730faeff8f216b8c

**Comment by amutake** [comment]
Thank you for the quick fix :bow: :bow:
