### ISSUE TITLE
Display article's status in list

### ISSUE THREAD

**Issue by onk** [rutan/potmum#33]
Is there a reason to hide the status of articles in the list?

Like counts and comment counts are indicator for viewing articles, so I want to display them in list.
(Stock count should not be displayed because it is not displayed in `articles#show`.

If it is not the intended design, I will make pull request.

![image](https://user-images.githubusercontent.com/203046/32418476-ffa01d2a-c2ad-11e7-9285-fbc7ef4a725d.png)

**Comment by rutan** [comment]
Wow, sounds good to me :heart:
I don't intend to not display the scores. :pray:
